import { Metadata } from "next";
import CustomToolsClient from "./CustomToolsClient";

export const metadata: Metadata = {
    title: "AI Automation & Custom Business Tools | Mirage Tech AI",
    description: "Build custom software applications at the speed of thought. What are Custom Business Tools? It's our proprietary rapid MVP framework powered by AI.",
    openGraph: {
        title: "AI Automation & Custom Business Tools | Mirage Tech AI",
        description: "Build custom software in days, not months.",
        url: "https://miragetech.ai/services/vibe-coding",
    },
};

export default function CustomToolsPage() {
    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify({
                        "@context": "https://schema.org",
                        "@type": "FAQPage",
                        "mainEntity": [
                            {
                                "@type": "Question",
                                "name": "What are Custom Business Tools?",
                                "acceptedAnswer": {
                                    "@type": "Answer",
                                    "text": "Custom Business Tools are rapid software solutions where we build applications using AI-accelerated workflows. We focus on translating business needs into production-ready code almost instantly, shortening the concept-to-MVP timeline from months to days."
                                }
                            },
                            {
                                "@type": "Question",
                                "name": "How fast can I launch a custom tool?",
                                "acceptedAnswer": {
                                    "@type": "Answer",
                                    "text": "For a standard custom tool or MVP, Mirage Tech AI can deliver a fully functional, deployed web application in under 7 days using our AI-accelerated frameworks."
                                }
                            },
                            {
                                "@type": "Question",
                                "name": "Is code generated by AI scalable and secure?",
                                "acceptedAnswer": {
                                    "@type": "Answer",
                                    "text": "Absolutely. Mirage Tech AI uses enterprise-grade stacks like Next.js, full-stack TypeScript, and Supabase. The AI acts as an accelerator, but senior engineers architect the security, scalability, and infrastructure."
                                }
                            }
                        ]
                    })
                }}
            />
            <CustomToolsClient />
        </>
    );
}
