import { Metadata } from "next";
import VibeCodingClient from "./VibeCodingClient";

export const metadata: Metadata = {
    title: "Vibe Coding & Rapid AI Development | Mirage Tech AI",
    description: "Build custom software applications at the speed of thought. What is Vibe Coding? It's our proprietary rapid MVP framework powered by AI.",
    openGraph: {
        title: "Vibe Coding | Mirage Tech AI",
        description: "Build custom software in days, not months.",
        url: "https://miragetech.ai/services/vibe-coding",
    },
};

export default function VibeCodingPage() {
    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify({
                        "@context": "https://schema.org",
                        "@type": "FAQPage",
                        "mainEntity": [
                            {
                                "@type": "Question",
                                "name": "What is Vibe Coding?",
                                "acceptedAnswer": {
                                    "@type": "Answer",
                                    "text": "Vibe Coding is a rapid software development methodology where developers write applications asynchronously using AI copilots and generative models. It focuses on translating human intent ('vibes') into production-ready code almost instantly, shortening the concept-to-MVP timeline from months to days."
                                }
                            },
                            {
                                "@type": "Question",
                                "name": "How fast can I launch an app with Vibe Coding?",
                                "acceptedAnswer": {
                                    "@type": "Answer",
                                    "text": "For a standard MVP (Minimum Viable Product), Mirage Tech AI can deliver a fully functional, deployed web application in under 7 days using our Vibe Coding frameworks."
                                }
                            },
                            {
                                "@type": "Question",
                                "name": "Is code generated by AI scalable and secure?",
                                "acceptedAnswer": {
                                    "@type": "Answer",
                                    "text": "Absolutely. Mirage Tech AI uses enterprise-grade stacks like Next.js, full-stack TypeScript, and Supabase. The AI acts as an accelerator, but senior engineers architect the security, scalability, and infrastructure."
                                }
                            }
                        ]
                    })
                }}
            />
            <VibeCodingClient />
        </>
    );
}
